_wandb:
    value:
        cli_version: 0.24.0
        e:
            zbzr2ycdapd0bqwczxomsdb7sisfzu26:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                args:
                    - --epochs
                    - "3"
                    - --run-name
                    - wandb_smoke_test_1
                codePath: src/group_56/train.py
                codePathLocal: src/group_56/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "167458578432"
                email: s252976@dtu.dk
                executable: /Users/alessandra/miniforge3/envs/fish_mlops/bin/python
                git:
                    commit: 8c866a713aafc37d8015c0d63153076fc606d999
                    remote: https://github.com/FergadakisN/group56.git
                host: 192.168.1.72
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/alessandra/Desktop/DTU/ML_Operations/group56/src/group_56/train.py
                python: CPython 3.10.19
                root: /Users/alessandra/Desktop/DTU/ML_Operations/group56
                startedAt: "2026-01-18T17:30:23.269254Z"
                writerId: zbzr2ycdapd0bqwczxomsdb7sisfzu26
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.19
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
amp:
    value: true
arch:
    value: resnet18
batch_size:
    value: 32
ckpt_name:
    value: last.pt
epochs:
    value: 3
freeze_backbone:
    value: false
lr:
    value: 0.0003
pretrained:
    value: true
processed_dir:
    value: data/processed
save_best:
    value: true
seed:
    value: 42
unfreeze_from:
    value: null
weight_decay:
    value: 0.0001
